### ISSUE TITLE
http://magiciengatineau.com/e-promo-kit/

### ISSUE THREAD

**Issue by Clownatec01** [cmarois/catec#136]
Pourrais tu arranger la form au bas . J'aimerais avoir le même style (avec les boites bleu) comme contactez-nous
ordi, ipad, telephone

**Comment by cmarois** [comment]
E-promot-kit est responsive

**Comment by Clownatec01** [comment]
Super

**Comment by Clownatec01** [comment]
Hello!

 

Important message, visit http://kalitelimatbaa.com/walked.php?nfw0

 

info@clownatec.com
