### ISSUE TITLE
magiciengatineau.com

### ISSUE THREAD

**Issue by Clownatec01** [cmarois/catec#137]
peux-tu ajouter dans la partie gris complètement en haut a côté du logo facebook, un bouton english
pour que le client puisse changer de langue

**Comment by cmarois** [comment]
J'ai trouvé ou l'info est rentrée pour la barre grise, mais je peux pas rien ajouter la.  C'est des options predefinies. On peut ajouter au menu juste en dessus, apres 'contactez nous'  ?

**Comment by cmarois** [comment]
Pour que tu check, j'ai ajouter un item "English" au menu principal.   Et je redirige aux pages correcspondantes sur le site anglais.  (j'ai pas fait toutes les pages, mais celles qui sont associées au menu principal,   spectacles, animation, etc).
Si je trouve pas de page ou rediriger, je vais a l'accueil  anglais.

**Comment by Clownatec01** [comment]
Christian 

Je comprends la complexité.... mais si on le redirige vers le site
anglais. qu'est ce que ca fait visuellement pour le client. car je
présume que cela va toujours ce produire sur la page d'acceuil. 

merci 

On 2014-11-12 07:34 PM, cmarois wrote: 

> Ok, ca je suis moins familier avec cette partie, alors voici quelques questions: 
> 
> La barre grise en haut fait partie d'un header general au site. Je sais pas ou il se trouve, et faudrait que je sache pour ajouter quelque chose la. 
> 
> Maintenant, il y a 2 manieres de changer la langue:
> 1- facile et basic (moins professionel) ; rediriger a l'acceuil du site anglais
> 2- expected behavior ; rester sur la meme page, mais qui change en anglais. 
> 
> Maintenant, je sais bien que tu veux le #2 [1] et c'est comment ca marche.. hmmm. partout, mais voici une difficulté avec ton site (qui n'est pas insurmontable). Ta page anglaise de n'importe quelle page francaise se trouve sur un autre site, avec un autre nom de page completement different. Bien souvent les site vont etre un peu comme ton ancien, http://host.ca/en/home [2] et http://host.ca/fr/home [3], ce qui fait que tu change la partie "langue" du url et voila. Mais ici, on peut pas faire ca. Et vu que tu le positionne dans un header general au site, et ou chaque page doit rediriger a une autre page specifique, la complexité monte. 
> 
> Ceci etant dit, voici comment je vois la solution: Il faudrait que l'option de la langue s'en aille a une page de redirection, et que la page de redirection ait une "map" ou il faudra mettre les pages anglais et francais en relation, alors cette page de redirection cherche la page d'ou elle provient (ou tu etait juste avant) et trouve vers quelle page elle doit s'en aller. 
> 
> --
> Reply to this email directly or view it on GitHub [4].
 

Links:
------
[1] https://github.com/cmarois/catec/issues/2
[2] http://host.ca/en/home
[3] http://host.ca/fr/home
[4] https://github.com/cmarois/catec/issues/137#issuecomment-62821650

**Comment by Clownatec01** [comment]
oubli l'autre message super ca fonctionne 

On 2015-01-08 02:12 PM, cmarois wrote: 

> Pour que tu check, j'ai ajouter un item "English" au menu principal. Et je redirige aux pages correcspondantes sur le site anglais. (j'ai pas fait toutes les pages, mais celles qui sont associées au menu principal, spectacles, animation, etc).
> Si je trouve pas de page ou rediriger, je vais a l'accueil anglais. 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/cmarois/catec/issues/137#issuecomment-69231729

**Comment by Clownatec01** [comment]
Hello!

 

New message, please read <http://tanstore.com.tr/resolved.php?f7la>

 

info@clownatec.com

**Comment by Clownatec01** [comment]
Hi,

I think I 've just found some information that may be helpfull to you, read it here please <http://nduthatrondo.teriholdren.com/aehzj>

Take care, info@clownatec.com
