### ISSUE TITLE
http://magiciengatineau.com/pourquoi-nous/

### ISSUE THREAD

**Issue by Clownatec01** [cmarois/catec#138]
telephone 
le tableau pas responsive

**Comment by cmarois** [comment]
La table est maintenant responsive.

**Comment by Clownatec01** [comment]
Il réduit sur le téléphone je vois les 4 colones de mes concurrants mais quand il est grand je vois juste 2 colones de mes concurrants

**Comment by cmarois** [comment]
Je vois pas ce que tu veux dire, j'ai essayer sur plusieurs formats et je vois toujours les 4 colonnes.
