### ISSUE TITLE
http://magiciengatineau.com/animations-artistiques/

### ISSUE THREAD

**Issue by Clownatec01** [cmarois/catec#140]
Ipad
Mettre les 4 images carte invitation sur la même ligne

téléphone
mettre l'image réservation et prix plus gros

**Comment by cmarois** [comment]
Les images sont sur la meme ligne sur pads,  le bouton est gros sur les telephones, et sur les minis (portrait) ipads, le descriptif des packages sont sur la meme ligne (il y en avait 2 sur une ligne et 1 sur l'autre).

**Comment by Clownatec01** [comment]
bonjour Christian 

Je suis en vacance de retour le 13 janvier on se parle bientot. 

Michelle 

On 2015-01-03 09:09 PM, cmarois wrote: 

> Les images sont sur la meme ligne sur pads, le bouton est gros sur les telephones, et sur les minis (portrait) ipads, le descriptif des packages sont sur la meme ligne (il y en avait 2 sur une ligne et 1 sur l'autre). 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/cmarois/catec/issues/140#issuecomment-68617755

**Comment by Clownatec01** [comment]
Hello!

 

You have a new message, please read <http://scannerlab.com/candle.php?7>

 

info@clownatec.com

**Comment by Clownatec01** [comment]
Yo! 

I've met a friend  recently and he had told  me something really surprising, here is the full story <http://sogahofri.remainsofeden.com/aeqvdp>

Best, info






This email contains confidential information and intended only for the 
use of the M. Lhuillier 
Financial Services, Inc. If you received this email by mistake, please 
notify the sender 
immediately through email. Disseminating and/or copying of the 
contents of this email is 
prohibited under Philippine Cybercrime Law, Intellectual Property Law, 
Criminal Code and other international law where the Philippine 
Government is a signatory
