### ISSUE TITLE
http://newsite.clownatec.com/fete-enfants-contactez-nous/

### ISSUE THREAD

**Issue by Clownatec01** [cmarois/catec#143]
- [x] date of event le calendrier apparait pas

- [x] quand  la form est vide et que tu click il ne met pas les boite rouge sur les fiels obligatoire.

**Comment by cmarois** [comment]
Fixed

**Comment by Clownatec01** [comment]
fonctionne pas chez moi ni chrome ni firefox le calendrier pour qu'il choisit la date et l'anné

chrome fonctionne pour la boite rouge mais pas firefox

**Comment by cmarois** [comment]
Essayer de clearer le cache

**Comment by cmarois** [comment]
RE-fixed

**Comment by Clownatec01** [comment]
parfait
